/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/8pIzB4GCiUH
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card"
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "@/components/ui/table"
import { Badge } from "@/components/ui/badge"

export function Component() {
  return (
    (<Card className="w-full max-w-4xl">
      <CardHeader>
        <CardTitle>Billing</CardTitle>
        <CardDescription>Review your monthly payment history.</CardDescription>
      </CardHeader>
      <CardContent>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Month</TableHead>
              <TableHead>Status</TableHead>
              <TableHead className="text-right">Amount</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            <TableRow>
              <TableCell>June 2023</TableCell>
              <TableCell>
                <Badge variant="outline" className="bg-green-500 text-green-50">
                  Paid
                </Badge>
              </TableCell>
              <TableCell className="text-right">$99.99</TableCell>
            </TableRow>
            <TableRow>
              <TableCell>May 2023</TableCell>
              <TableCell>
                <Badge variant="outline" className="bg-red-500 text-red-50">
                  Not Paid
                </Badge>
              </TableCell>
              <TableCell className="text-right">$99.99</TableCell>
            </TableRow>
            <TableRow>
              <TableCell>April 2023</TableCell>
              <TableCell>
                <Badge variant="outline" className="bg-green-500 text-green-50">
                  Paid
                </Badge>
              </TableCell>
              <TableCell className="text-right">$99.99</TableCell>
            </TableRow>
            <TableRow>
              <TableCell>March 2023</TableCell>
              <TableCell>
                <Badge variant="outline" className="bg-green-500 text-green-50">
                  Paid
                </Badge>
              </TableCell>
              <TableCell className="text-right">$99.99</TableCell>
            </TableRow>
            <TableRow>
              <TableCell>February 2023</TableCell>
              <TableCell>
                <Badge variant="outline" className="bg-green-500 text-green-50">
                  Paid
                </Badge>
              </TableCell>
              <TableCell className="text-right">$99.99</TableCell>
            </TableRow>
            <TableRow>
              <TableCell>January 2023</TableCell>
              <TableCell>
                <Badge variant="outline" className="bg-green-500 text-green-50">
                  Paid
                </Badge>
              </TableCell>
              <TableCell className="text-right">$99.99</TableCell>
            </TableRow>
          </TableBody>
        </Table>
      </CardContent>
    </Card>)
  );
}
